### ISSUE TITLE
add new type (stackbar)

### ISSUE THREAD

**Issue by golriz** [seangofus/who-charted#2]
I want to add another type of chart (stackbar ) , already written as Chart.StackedBar.js
(https://github.com/Regaddi/Chart.StackedBar.js) .
I want to embed it.
could you help where do I begin ?
thanks

**Comment by ahmadgolzar** [comment]
Hi,

I have the same question. How can I add the Chart.StackedBar.js plugin? Can you please provide a step by step instruction. It will be so much appreciated.

Thanks

**Comment by seangofus** [comment]
@golriz and @ahmadgolzar I will provide steps or an actual implementation for this later tonight when I get home.

**Comment by seangofus** [comment]
Sorry guys this is a little more complicated then it appeared on the surface. The StackedBar source does a check for an AMD implementation, which Oro uses however the chart.js definition does not match what this bundles currently uses, so I will have to refactor. This will take a little longer than anticipated please stand by. Thanks.

**Comment by golriz** [comment]
@seangofus  thanks a lot

**Comment by ahmadgolzar** [comment]
@seangofus thank you so much for your instant reply. Looking forward to see the result :)

**Comment by seangofus** [comment]
I just wanted to provide a quick update on this issue. I have pushed code to allow the stacked bar chart type. However I am waiting for the Oro packagist to pick up the changes so I can do one more quick run through before providing the required steps. Thank you for your patience.

**Comment by ahmadgolzar** [comment]
Hi Sean,
Thanks for the update. Any recent news from the packagist?

**Comment by seangofus** [comment]
Yes. Oro's packagist is now updated. You should be able to run a composer update to get the recent changes. If that doesn't work you may want to try deleting you composer.lock file and then run composer update.

I have updated the README https://github.com/seangofus/who-charted/blob/master/README.md with the stacked bar options. Basically you would use it the same way as a bar chart the only difference is for the name option you would specify 'stacked_bar_chart' instead of 'bar_chart' like so: 

``` php
// ... other code up here

$widgetAttr['chartView'] = $this->get('who.charted')
            ->setArrayData($data)
            ->setOptions(
                array(
                    'name' => 'stacked_bar_chart',
                    'settings' => array(
                        'animation' => true,
                        'legend' => true
                    )
                )
            )
            ->getView();
```

Let me know if this helps or you if you are running into issues. Thanks.

**Comment by seangofus** [comment]
@golriz or @ahmadgolzar can this issue now be closed?

**Comment by golriz** [comment]
@seangofus  I must say big thanks to you , it works , it help me very much and out team enjoyed it :)

just I change some lines

line 84 of  Chart.StackBar.js : 
    sum += parseInt(datasets[i].bars[barIndex].value);
line 114: 
    sum += parseInt(datasets[i].bars[barIndex].value);  
line 260 :
    if (dataCollection[dataIndex] && dataCollection[dataIndex].value)
line 280 :
        total.value += parseInt(element.value);

 line 6 of stack-bar-chart-component: 
        StackedBar = require('StackedBar'),

regards,
Golriz

**Comment by seangofus** [comment]
@golriz glad it helped ... Could you possibly post your requirejs.yml config for the StackedBar component that you changed? While I was adding support for stacked bar charts I had trouble using the named module hence the reason I just used a path instead. I am curious what you had to do to get it to work.

**Comment by ahmadgolzar** [comment]
Dear @seangofus 
Thank you so much. This was a great help to us. Thanks @golriz for your feedback.

**Comment by golriz** [comment]
Dear @seangofus 
I don't change requirejs.yml  file, as you can see :

config:
    paths:
        'Chart': 'bundles/jovwhocharted/lib/chart/Chart.min.js'
        'StackedBar': 'bundles/jovwhocharted/lib/chart/Chart.StackedBar.js'
        'jovwhocharted/js/app/components/base-chart-component': 'bundles/jovwhocharted/js/app/components/base-chart-component.js'
        'jovwhocharted/js/app/components/pie-chart-component': 'bundles/jovwhocharted/js/app/components/pie-chart-component.js'
        'jovwhocharted/js/app/components/bar-chart-component': 'bundles/jovwhocharted/js/app/components/bar-chart-component.js'
        'jovwhocharted/js/app/components/line-chart-component': 'bundles/jovwhocharted/js/app/components/line-chart-component.js'
        'jovwhocharted/js/app/components/radar-chart-component': 'bundles/jovwhocharted/js/app/components/radar-chart-component.js'
        'jovwhocharted/js/app/components/polar-chart-component': 'bundles/jovwhocharted/js/app/components/polar-chart-component.js'
        'jovwhocharted/js/app/components/doughnut-chart-component': 'bundles/jovwhocharted/js/app/components/doughnut-chart-component.js'
        'jovwhocharted/js/app/components/stacked-bar-chart-component': 'bundles/jovwhocharted/js/app/components/stacked-bar-chart-component.js'
