### ISSUE TITLE
color of bar chart

### ISSUE THREAD

**Issue by golriz** [seangofus/who-charted#3]
I create a bar chart with 2 series , so I set below setting but I see charts all in same color
I omit my color setting but default colors of "who_charted.yml" does not work! just first color is used 
also I want to see my legend colored but I see then clack with bullet

                    'settings' => array(
                        'colors' =>
                            [[ 'fillColor' => 'rgba(220,220,220,0.2)',
                                'strokeColor'=> 'rgba(220,220,220,1)',
                                'pointColor'=> 'rgba(220,220,220,1)',
                                'pointStrokeColor'=> '#fff',
                                 'pointHighlightFill'=> '#fff',
                                 'pointHighlightStroke'=> 'rgba(220,220,220,1)'],
                                [ 'fillColor' => 'rgba(151,187,205,0.2)',
                                    'strokeColor'=> 'rgba(151,187,205,1)',
                                    'pointColor'=> 'rgba(151,187,205,1)',
                                    'pointStrokeColor'=> '#fff',
                                    'pointHighlightFill'=> '#fff',
                                    'pointHighlightStroke'=> 'rgba(151,187,205,1)']],
                                'barValueSpacing' => 50,
                        'animation' => true,
                        'legend'=>true
                    )
could you help me , what should I do?
thanks

**Comment by seangofus** [comment]
@golriz Could you please provide a screenshot so I can help debug for you better. Thanks.

**Comment by golriz** [comment]
I am so late :( sorry
![chart](https://cloud.githubusercontent.com/assets/8477560/13194604/5247a6cc-d7ac-11e5-8ad6-82d82c749c4f.jpg)

**Comment by golriz** [comment]
I forgot say about legend ,could you help me about legend too?

**Comment by seangofus** [comment]
Hello @golriz I tried to reproduce your color issue however I believe it is working correctly for me. I have tried to reproduce your "items" data array as best as I could. See the screenshot below: 
![screen shot 2016-02-20 at 2 39 26 pm](https://cloud.githubusercontent.com/assets/1251177/13199068/59a1b2b2-d7e0-11e5-8485-6aa2cb940578.png)

As you can see the violet and blue colors are showing as specified. I also tried removing the color options entirely and the default colors take over as expected. So unfortunately I am unable to reproduce the issue. Here is the code I used to try to replicate what you are seeing.
```php
$items = array(
    'labels' => array("default", "doctor", "group 2", "group 1", "group 3", "nurse"),
    "datasets" => array(
        array('data' => array(0, 1, 5, 0, 0, 0)),
        array('data' => array(0, 0))
    )
);
$widgetAttr = $this->get('oro_dashboard.widget_configs')->getWidgetAttributesForTwig($widget);
$widgetAttr['chartView'] = $this->get('who.charted')
    ->setArrayData($items)
    ->setOptions(
        array(
            'name' => 'bar_chart',
            'settings' => array(
                'colors' => [
                    [
                        'fillColor' => 'rgba(170,122,205,0.5)',
                        'strokeColor'=> 'rgba(170,122,205,0.8)',
                        'highlightFill'=> 'rgba(170,122,205,0.75)',
                        'highlightStroke'=> 'rgba(170,122,205,1)'
                    ],
                    [
                         'fillColor' => 'rgba(151,187,205,0.5)',
                         'strokeColor'=> 'rgba(151,187,205,0.8)',
                         'highlightFill'=> 'rgba(151,187,205,0.75)',
                         'highlightStroke'=> 'rgba(151,187,205,1)'
                    ]
                ],
                'barValueSpacing' => 50,
                'animation' => true,
                'legend' => true
            )
        )
    )
    ->getView();
```
I tried to reproduce the data array solely based on the screenshot you provided. If you provide me with a sample of the data array I would be happy to look at it again.

As far as the legend goes. All this bundle does is output it the same way the Chart.js library would. So right now it is outputting an unformatted unordered list. You can style it with your own CSS. If you would like I could perhaps enhance this bundle by offering some default styles for the legend, but that is beyond  the scope of this issue. If you do want default styling please open another issue. Thanks.

**Comment by golriz** [comment]
thanks a lot for your sample code
I found that I set key for each series(array) of datasets but I should set number index 
incorrect : datasets [[label1]['data'=>[1,2,3]] , [label2]['data'=>[0,2,0]]]
correct : datasets [[0]['data'=>[1,2,3]] , [1]['data'=>[0,2,0]]]
thanks a lot

**Comment by seangofus** [comment]
You are welcome.
